---
name: Build Power Apps

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-power-apps:
    name: Build Power Apps
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: Setup node equally to our local development version
        if: steps.npm-cache.outputs.cache-hit != 'true'
        # pick the Node version to use and install it
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Display node and npm version
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          node --version
          npm --version

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: ⬇ Download foundations build
        uses: ./.github/actions/download-tar-artifact
        with:
          name: db-ui-foundations-build
          path: packages/foundations/build

      - name: ⬇ Download output
        uses: ./.github/actions/download-tar-artifact
        with:
          name: db-ui-output
          path: output

      - name: 🖨 Copy Power Apps
        run: npm run copy:power-apps

      - name: 🔨 Build Power Apps
        env:
          VALID_SEMVER_VERSION: ${{ inputs.version }}
        run: |
          cd build-power-apps
          npm i
          cd DBUI
          STRIPED_VERSION=${VALID_SEMVER_VERSION%-*}
          npx replace-in-file 0.0.0 ${STRIPED_VERSION//-/.} src/Other/Solution.xml
          dotnet build --configuration Release

      - name: ⬆ Upload Power Apps zip
        uses: ./.github/actions/upload-tar-artifact
        with:
          name: db-ui-powerapps
          path: build-power-apps/DBUI

      - name: 💀 Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
