---
name: Default Pipeline

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  init:
    uses: ./.github/workflows/00-init.yml

  scan-secrets:
    if: github.event.pull_request == null || github.event.pull_request.head.repo.owner.login == 'db-ui'
    uses: ./.github/workflows/00-scan-secrets.yml

  lint:
    uses: ./.github/workflows/01-lint.yml
    needs: [init]

  build-packages:
    uses: ./.github/workflows/01-build-packages.yml
    needs: [init]

  build-outputs:
    uses: ./.github/workflows/01-build-outputs.yml
    needs: [build-packages]

  test-packages:
    uses: ./.github/workflows/02-e2e.yml
    needs: [build-packages]

  build-showcases:
    uses: ./.github/workflows/01-build-showcases.yml
    needs: [build-packages]

  build-power-apps:
    uses: ./.github/workflows/01-build-power-apps.yml
    needs: [build-packages]
    secrets: inherit
    with:
      version: 0.0.0-test

  checks-done:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: 🎉 Checks done
        run: |
          result-build-showcases="${{ needs.build-showcases.result }}"
          result-build-outputs="${{ needs.build-outputs.result }}"
          result-test-packages="${{ needs.test-packages.result }}"
          result-build-power-apps="${{ needs.build-power-apps.result }}"
          if [[ $result-build-showcases == "success" && $result-build-outputs == "success" && $result-test-packages == "success" && $result-build-power-apps == "success" ]]; then
             echo "🎉 All tests were successful."
            exit 0
          else
             echo "Some tests were failing."
            exit 1
          fi
    needs: [build-showcases, build-outputs, test-packages, build-power-apps]

  deploy:
    uses: ./.github/workflows/03-deploy-gh-pages.yml
    if: ${{ github.actor != 'dependabot[bot]' && (github.event.pull_request == null || github.event.pull_request.head.repo.owner.login == 'db-ui') }}
    needs: [checks-done]
    with:
      release: false
      preRelease: false
