---
name: Update all PR branches if main gets update

on:
  push:
    branches:
      - "main"

jobs:
  update-prs:
    name: Update PRs
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: Setup node equally to our local development version
        if: steps.npm-cache.outputs.cache-hit != 'true'
        # pick the Node version to use and install it
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Display node and npm version
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          node --version
          npm --version

      - name: ⌚ Update PRs
        id: cleanup
        uses: actions/github-script@v6
        with:
          script: |
            // TODO: we need to wait for some results on https://github.com/orgs/community/discussions/43427 for this one
            // const { default: updatePrs } = await import('${{ github.workspace }}/.github/scripts/update-prs.js');
            // print how many PRs are updated
            // console.log(await updatePrs({github, context}));
